defmodule Exins.Repo.Migrations.AddContactDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:contacts) do
      add :phones, {:array, :map}, null: false
      add :addresses, {:array, :map}, null: false
      add :emails, {:array, :map}, null: false
    end
  end

  def down do
    alter table(:contacts) do
      remove :emails
      remove :addresses
      remove :phones
    end
  end
end
