defmodule Exins.Repo.Migrations.AddContactsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :names, {:array, :map}, null: false
    end
  end

  def down do
    drop table(:contacts)
  end
end
